baseURL = 'https://www.clubdulevain.ch/'
languageCode = 'fr-ch'
title = 'Club du Levain'
theme = 'ananke'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10

[params]
    date_format = "2 January 2006"
    text_color = ""
    author = ""
    favicon = "/favicon.png"
    site_logo = ""
    description = "The last theme you'll ever need. Maybe."
    # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    recent_posts_number = 6
    mainSections = "posts"
